name: Nuget Deploy

on:
  # Trigger the workflow on push but only for the master branch
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@master

            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.1

            - name: Build package
              run: dotnet pack NAudio\NAudio.csproj --configuration release -p:PackageVersion=2.2.${{ github.run_number }}

            - name: Publish package
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              run: dotnet nuget push "NAudio\bin\release\NAudio.2.2.${{ github.run_number }}.nupkg" --source "https://nuget.pkg.github.com/umg/index.json" --api-key $env:GITHUB_TOKEN